Feature/kp view employees component
NSS-Day-Cohort-73/Shepherd-s-Pie-client-rlmafc pull request #28
Opened 2024-11-06 21:30 UTC by kennypanyavong

2024-11-06 21:54 UTC, herringvoices requested changes

2024-11-06 21:54 UTC, herringvoices commented on src/components/employees/EmployeeDetails.jsx
> +          `http://localhost:8088/employees/${employeeId}`
Write a function for this in employee services and call it here.

2024-11-06 21:54 UTC, herringvoices commented on src/components/employees/EmployeeDetails.jsx
> +          `http://localhost:8088/employees/${employeeId}`
```
export const getEmployees = async (employeeId) => {
  try {
const url = employeeId
    ? `[http://localhost:8088/employees/${employeeId}](http://localhost:8088/employees/$%7BemployeeId%7D)`
    : "http://localhost:8088/employees";
    const response = await fetch(url);
    const employees = await response.json();
    return employees;
  } catch (error) {
    console.error("Error fetching employees:", error);
  }
};
```

2024-11-06 21:54 UTC, herringvoices commented on src/components/employees/EmployeeDetails.jsx
> +  // handle delete employee
There is a service for this in employeeServices that you can call inside your handler function.

2024-11-06 21:54 UTC, herringvoices commented on src/components/employees/EmployeeDetails.jsx
> +  // get employeeId from the url
useNavigate() could be set up here:
`  const navigate = useNavigate();`

2024-11-06 21:54 UTC, herringvoices commented on src/components/employees/EmployeeDetails.jsx
> +  //     useNavigate("/employees/view") //insert route
then here, you would just be using navigate:
`navigate(`/employees/edit/employeeId`)`

2024-11-06 21:54 UTC, herringvoices commented on src/components/employees/EmployeeDetails.jsx
> +  // handle delete employee
then handleEditEmployee will use call the `updateEmployee()` function passing in the employee object.

2024-11-07 16:36 UTC, herringvoices approved these changes

2024-11-07 16:36 UTC, joshuaKsmith approved these changes

2024-11-07 16:37 UTC, merged